# Generated by Django 2.1.4 on 2018-12-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='9', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='radmin_app.Activity')),
                ('activity_date', models.DateField()),
            ],
            bases=('radmin_app.activity',),
        ),
        migrations.CreateModel(
            name='RepeatedActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='radmin_app.Activity')),
            ],
            bases=('radmin_app.activity',),
        ),
    ]
