# Generated by Django 2.1.4 on 2018-12-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('activity_date', models.DateField()),
            ],
            bases=('activities.activity',),
        ),
    ]
