# Generated by Django 2.1.4 on 2018-12-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_onetimeactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '1'), ('12', '12')], default='9', max_length=2)),
            ],
        ),
    ]
