# Generated by Django 2.1.4 on 2018-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='9', max_length=2)),
                ('student_score', models.IntegerField()),
            ],
        ),
    ]
