# Generated by Django 2.1.4 on 2019-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_pass',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
