# Generated by Django 2.1.4 on 2019-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190115_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_history',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
